version: '3.4'

services:
  singleapp:
    image: docker-dev.artifacts.dips.local/single/single:latest
    ports:
      - "80:5000"
    environment:
      - SINGLE_MusixmatchApiKey=${MUSIXMATCH_APIKEY}
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        commit_id: ${COMMIT_ID}